# Generated by Django 4.2 on 2023-05-07 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Resenas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=25)),
                ('fecha_creación', models.DateField(default='2023-05-07')),
                ('titulo', models.CharField(max_length=25)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.ImageField(upload_to='')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resenas.categorias')),
            ],
        ),
    ]
