# Generated by Django 4.2 on 2023-05-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenas', '0005_alter_resenas_fecha_creación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenas',
            name='fecha_creación',
            field=models.DateField(default='2023-05-14'),
        ),
    ]
