# Generated by Django 4.2 on 2023-05-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenas', '0007_alter_resenas_fecha_creación'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenas',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='resenas/files/images'),
        ),
    ]
