# Generated by Django 4.2 on 2023-05-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenas', '0008_resenas_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='resenas',
            name='fecha_creación',
            field=models.DateField(default='2023-05-16'),
        ),
        migrations.AlterField(
            model_name='resenas',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/resenas'),
        ),
    ]
