# Generated by Django 4.2 on 2023-05-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenas', '0008_resenas_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenas',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/resenas'),
        ),
    ]
