# Generated by Django 4.2 on 2023-06-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resenas', '0009_alter_categorias_nombre_alter_resenas_fecha_creación_and_more'),
        ('resenas', '0011_alter_resenas_fecha_creación'),
    ]

    operations = [
    ]
