# Generated by Django 4.2 on 2023-06-01 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resenas', '0011_resenas_valoracion_alter_resenas_fecha_creación'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resenas',
            name='valoracion',
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resenas.resenas')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
