# Generated by Django 4.2 on 2023-06-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resenas', '0012_merge_20230604_1900'),
        ('resenas', '0014_alter_resenas_fecha_creación'),
    ]

    operations = [
    ]
