# Generated by Django 4.2 on 2023-06-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenas', '0015_merge_20230616_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenas',
            name='fecha_creación',
            field=models.DateField(default='2023-06-27'),
        ),
    ]
